name: CI workflow

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Unit Tests
        run: npm test
